### ISSUE TITLE
请问如何根据爬到的内容继续往下爬？

### ISSUE THREAD

**Issue by nielinjie** [fengzhizi715/NetDiscovery#14]
请问如何根据爬到的内容继续往下爬？比如要跟着这个页面上的链接爬下一个页面。
自己实现parser，parse到目标地址，然后创建新的爬虫？

**Comment by fengzhizi715** [comment]
可以编写一个PipeLine，然后启动另一个爬虫。

**Comment by nielinjie** [comment]
但pipeline的接口方法里面只有resultitems可以用。自己去连接 queue或者spiderEngine？

**Comment by fengzhizi715** [comment]
hi @nielinjie 今天在Pipeline接口中加了两个default方法，可以用于深度爬取。
