### ISSUE TITLE
spiderEngine启动后访问URL都是404

### ISSUE THREAD

**Issue by nielinjie** [fengzhizi715/NetDiscovery#15]
spiderEngine启动后访问URL都是404。
比如http://localhost:7070/netdiscovery/spiders/

**Comment by fengzhizi715** [comment]
SpiderEngine 绑定的端口号是7070嘛？

**Comment by nielinjie** [comment]
不是7070就不会是404，而是连不上啊。

**Comment by fengzhizi715** [comment]
方便的话加一下我微信把工程给我，我帮你看一下。
微信号跟github账号相同。

**Comment by nielinjie** [comment]
dashboard还是404。
我只引用了core和dsl，是不是还要别的包？

**Comment by fengzhizi715** [comment]
hi @nielinjie  不好意思，dashboard 其实只是给自己使用的一个小工具。

如果需要使用的话，先启动agent模块。在工程中，agent模块先导出一个fat jar，然后使用如下的命令启动：java -jar agent-1.0-SNAPSHOT-fat.jar

接下来，spiderEngine 需要打开监控：
spiderEngine.setUseMonitor(true);

这样才能使用dashboard。
