### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by guoleifei** [fengzhizi715/NetDiscovery#18]
![image](https://user-images.githubusercontent.com/16201257/63936371-3da88100-ca92-11e9-98c3-5f21b1dc07e4.png)
不知道 idea 环境都已经设置了 UTF-8
文字删除重写也不行。

![image](https://user-images.githubusercontent.com/16201257/63936444-692b6b80-ca92-11e9-9613-080d79b9c52f.png)
这个地方就这俩不行 
其他的类也是注解或是别的

**Comment by fengzhizi715** [comment]
用了lombok，需要打开Enable annotation processing
