### ISSUE TITLE
找不到依赖

### ISSUE THREAD

**Issue by starfire-lzd** [fengzhizi715/NetDiscovery#19]
core里面依赖了这个`cn.netdiscovery:config:1.0-SNAPSHOT`，下载不下来

**Comment by fengzhizi715** [comment]
不好意思，我晚上重新打一个包

**Comment by fengzhizi715** [comment]
hi @starfire-lzd 使用新的版本，不再需要那个config了

**Comment by starfire-lzd** [comment]
您好，我用了1.4.2，并没有解决这个问题

**Comment by starfire-lzd** [comment]
我看你master中core的gradle文件中还是依赖了config https://github.com/fengzhizi715/NetDiscovery/blob/master/core/core/build.gradle

**Comment by fengzhizi715** [comment]
我测了一下，确实是我的问题。config模块是最近新加的，没有详细测试，不好意思。
明早我会修复

**Comment by starfire-lzd** [comment]
我用了1.4.3修复还是无效的，config的代码是不是可以移到各自项目中，去除依赖，感觉config并没有拆出来的必要性

**Comment by fengzhizi715** [comment]
1.4.3 是我昨晚测试的。现在1.4.4已经修复了，可以尝试一下。
有问题可以微信联系我，wechat: fengzhizi715

**Comment by starfire-lzd** [comment]
可以使用了，非常感谢
