### ISSUE TITLE
maven 无法使用 kotlin DSL

### ISSUE THREAD

**Issue by XiuyeXYE** [fengzhizi715/NetDiscovery#20]
## Code:

import cn.netdiscovery.kotlin.dsl.request

fun main(){
    val req = request {
        url = "https://www.baidu.com/"

//        httpMethod = HttpMethod.GET

        spiderName = "tony"

        header {

            "111" to "2222"
            "333" to "44444"
        }

        extras {

            "tt" to "qqq"
        }
    }
}

## Error:

Kotlin: Cannot access class 'cn.netdiscovery.core.domain.Request'. Check your module classpath for missing or conflicting dependencies

## dependencies:

        <dependency>
            <groupId>cn.netdiscovery</groupId>
            <artifactId>netdiscovery-kotlin-dsl</artifactId>
            <version>1.4.5</version>
        </dependency>

        
        <dependency>
            <groupId>cn.netdiscovery</groupId>
            <artifactId>netdiscovery-kotlin-coroutines</artifactId>
            <version>1.4.5</version>
        </dependency>

## Anthor Error:
vertex 类的包也导入不进来 
![image](https://user-images.githubusercontent.com/16207730/137105427-c0ac2b0b-7301-4843-a714-2ef2f50efa90.png)
![image](https://user-images.githubusercontent.com/16207730/137105090-c61bde44-1b61-44b7-a022-ae342fa6ea24.png)

**Comment by fengzhizi715** [comment]
需要加一下jcenter()

```xml
<repositories>
    <repository>
        <id>central</id>
        <name>bintray</name>
        <url>https://jcenter.bintray.com</url>
    </repository>
</repositories>
```

**Comment by XiuyeXYE** [comment]
![image](https://user-images.githubusercontent.com/16207730/137136738-7580e56b-8aa1-4717-ab7f-280ef060ebf6.png)
![image](https://user-images.githubusercontent.com/16207730/137137657-9737993c-6423-4805-b1a7-1c744408a6ca.png)

本地有包但是，无法引入 vertx HttpMethod ，

**Comment by imtzc** [comment]
您好，邮件已经收到，我会尽快给您回复。
