### ISSUE TITLE
如何下载apk呢

### ISSUE THREAD

**Issue by xingstarx** [fengzhizi715/NetDiscovery#4]
比如说，我解析了一个页面，获取了当前页面的所有的apk的url，那么我该怎么下载呢，用你的这种Spider,可以给点说明么

其实我是不太明白，我有一个url 是 `http://www.xxx.apk ` ,我怎么使用类似这样的代码
```java
Spider.create(new PriorityQueue()).name("tony")
                .request(request3)
                .downloader(new HttpClientDownloader())
                .pipeline(new DebugPipeline())
                .run();

```
把apk下载下来保存到指定的目录呢，是需要自己对download进行定制么

**Comment by fengzhizi715** [comment]
@xingstarx 我在example module中添加了一个TestFile程序
展示了如何下载文件，并存放到指定的目录下。

**Comment by xingstarx** [comment]
赞，感谢回复
