### ISSUE TITLE
日志框架可否不限定死是logback呢

### ISSUE THREAD

**Issue by xingstarx** [fengzhizi715/NetDiscovery#6]
我有一个web项目，用的是log4j,把NetDiscovery相关的jar包引入进来，发现logback也引入进来了，这样就导致了冲突，实际上我不想使用logback

作者可否把日志框架设置成，可配置的呢，而不是一定是logback

**Comment by fengzhizi715** [comment]
hi @xingstarx，日志可以做成可配的，我晚点加一下

**Comment by fengzhizi715** [comment]
hi @xingstarx ，目前框架是使用logback+Slf4j
改成可配的话 可能要花一点时间。不急的话，等我一下，或者加我微信，微信号同github账号名。

**Comment by xingstarx** [comment]
嗯，可以的，我重新调整了下代码，发现目前并没有报错了，配置文件使用的依旧是log4j，爬虫的代码用的还是你这个，算是logback也还在里面
