### ISSUE TITLE
redisqueue 取出请求失败

### ISSUE THREAD

**Issue by bdqfork** [fengzhizi715/NetDiscovery#7]
在使用redisqueue的情况下，如果request有extra数据，从redisqueue取出请求时，取出的request所有属性字段为空，导致后续空指针异常

**Comment by fengzhizi715** [comment]
hi @bdqfork 已经修复这个bug，您可以再试一下

**Comment by bdqfork** [comment]
extra的依赖我发现很多都是runtime作用范围，导致直接编译失败，为什么不修改为complie呢

**Comment by fengzhizi715** [comment]
之前是使用compile，我周末再考虑一下吧
