### ISSUE TITLE
依赖冲突严重

### ISSUE THREAD

**Issue by bdqfork** [fengzhizi715/NetDiscovery#8]
在core,extra中很多依赖相互冲突，在mavenhelper中查看冲突的依赖如下
<img width="489" alt="2018-09-02 3 30 03" src="https://user-images.githubusercontent.com/23702980/44953249-18a42100-aec5-11e8-8ec7-73751731d74e.png">

**Comment by fengzhizi715** [comment]
@bdqfork  收到，我会尽快解决

**Comment by fengzhizi715** [comment]
hi @bdqfork  大部分依赖冲突解决了。

还剩下 bson 和 mongodb-driver-core 的，我看了一下core和extra模块没有单独使用它们。是 vertx-mongo-client 使用了它们，可以考虑在vertx-mongo-client中exclude它们，然后使用最新的版本。
