### ISSUE TITLE
爬虫是不是应该在爬虫队列为空时停止运行

### ISSUE THREAD

**Issue by bdqfork** [fengzhizi715/NetDiscovery#9]
看了源代码发现，爬虫在爬完队列里的任务就自动停止了。但是有些情况下需要在队列为空时爬虫阻塞，阻塞一段时间后，队列有任务时停止阻塞，继续爬取任务。还有一个问题是，有时候需要跟踪爬取链接，爬虫待爬取的链接是从xpath获取的链接，这个时候需要直接在parse之后添加到爬虫队列中。

**Comment by bdqfork** [comment]
对了，爬虫爬取数据的频率可以做一个限制吗，频率太高容易被封

**Comment by fengzhizi715** [comment]
hi @bdqfork Request类有一个属性sleepTime，可以对每次请求时先sleep一下。
另外两个问题我晚点回复你，下午公司的会比较多，抱歉。

**Comment by fengzhizi715** [comment]
hi @bdqfork 加一下我微信：
fengzhizi715
我已经邀请你成为这个项目的Collaborator

**Comment by bdqfork** [comment]
已经发了微信好友申请了，请确认一下
